version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: airquality_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airquality
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  # backend:
  #   build: ./
  #   container_name: airquality_backend
  #   command: npm run start:dev
  #   environment:
  #     DATABASE_URL: 'postgres://postgres:postgres@db:5432/airquality'
  #   ports:
  #     - '4000:4000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules

volumes:
  db_data:
